# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b24553a6eb44e1a377105bc57a6c505ab3503bf48a949cdcc033f21b5d8dcb943d26d6842a3d8d95455f9b492c3c487caf5923a02ed40f1c3d7ceea61bed94

test:
  secret_key_base: fe2b25725e0e13b532e6489b332544eccffc27d0145e610d42130eb822a9e3e196fbc9ecbff6b5e356834ec93be2cc1b1b6d0c58dba173892b1442fb2e8e448b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
